<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
  <head>
    <meta charset="utf-8" />
    <meta name="generator" content="pandoc" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=yes"
    />
    <title>solution</title>
    <style type="text/css">
      code {
        white-space: pre-wrap;
      }
      span.smallcaps {
        font-variant: small-caps;
      }
      span.underline {
        text-decoration: underline;
      }
      div.column {
        display: inline-block;
        vertical-align: top;
        width: 50%;
      }
    </style>
  </head>
  <body>
    <p>
      There are no tricks here. Just replace <code>.catch</code> with
      <code>try..catch</code> inside <code>demoGithubUser</code> and add
      <code>async/await</code> where needed:
    </p>
    <p>
      ``<code
        >js run class HttpError extends Error { constructor(response) {
        super(</code
      >${response.status} for ${response.url}`); this.name = ‘HttpError’;
      this.response = response; } }
    </p>
    <p>
      async function loadJson(url) { let response = await fetch(url); if
      (response.status == 200) { return response.json(); } else { throw new
      HttpError(response); } }
    </p>
    <p>
      // Ask for a user name until github returns a valid user async function
      demoGithubUser() {
    </p>
    <p>
      let user; while(true) { let name = prompt(“Enter a name?”, “iliakan”);
    </p>
    <pre><code>try {
  user = await loadJson(`https://api.github.com/users/${name}`);
  break; // no error, exit loop
} catch(err) {
  if (err instanceof HttpError &amp;&amp; err.response.status == 404) {
    // loop continues after the alert
    alert(&quot;No such user, please reenter.&quot;);
  } else {
    // unknown error, rethrow
    throw err;
  }
}      </code></pre>
    <p>}</p>
    <p>alert(<code>Full name: ${user.name}.</code>); return user; }</p>
    <p>demoGithubUser(); ```</p>
  </body>
</html>
