<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
  <head>
    <meta charset="utf-8" />
    <meta name="generator" content="pandoc" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=yes"
    />
    <title>solution</title>
    <style type="text/css">
      code {
        white-space: pre-wrap;
      }
      span.smallcaps {
        font-variant: small-caps;
      }
      span.underline {
        text-decoration: underline;
      }
      div.column {
        display: inline-block;
        vertical-align: top;
        width: 50%;
      }
    </style>
  </head>
  <body>
    <p>
      The difference becomes obvious when we look at the code inside a function.
    </p>
    <p>
      The behavior is different if there’s a “jump out” of
      <code>try...catch</code>.
    </p>
    <p>
      For instance, when there’s a <code>return</code> inside
      <code>try...catch</code>. The <code>finally</code> clause works in case of
      <em>any</em> exit from <code>try...catch</code>, even via the
      <code>return</code> statement: right after <code>try...catch</code> is
      done, but before the calling code gets the control.
    </p>
    <p>
      ```js run function f() { try { alert(‘start’); <em>!</em> return “result”;
      <em>/!</em> } catch (err) { /// … } finally { alert(‘cleanup!’); } }
    </p>
    <p>f(); // cleanup! ```</p>
    <p>…Or when there’s a <code>throw</code>, like here:</p>
    <p>
      ```js run function f() { try { alert(‘start’); throw new Error(“an
      error”); } catch (err) { // … if(“can’t handle the error”) {
      <em>!</em> throw err; <em>/!</em> }
    </p>
    <p>} finally { alert(‘cleanup!’) } }</p>
    <p>f(); // cleanup! ```</p>
    <p>
      It’s <code>finally</code> that guarantees the cleanup here. If we just put
      the code at the end of <code>f</code>, it wouldn’t run in these
      situations.
    </p>
  </body>
</html>
